### ISSUE TITLE
About the dimension of env features

### ISSUE THREAD

**Issue by shhuangcoder** [fairinternal/ego-env#1]
Hello, great job. But I have question, why I get an environment features of dimension (T, 128) after running:
   (python generate_env_features.py \
    --config state_prediction/config/downstream.yaml \
    --video /path/to/video.mp4 \
    --save env_feats.pth \
    MODEL.WEIGHTS checkpoints/cardinal_object_state/lightning_logs/version_0/checkpoints/epoch=2279-val_loss=2.29E-        01.ckpt). But readme says this generates a (T, 512) tensor for features sampled at 1FPS. 
I used the model downloaded from bash data/download_data.sh.

**Comment by Tushar-N** [comment]
Good catch, the environment features are indeed `(T, 128)` not `(T, 512)`. This is the `MODEL.HIDDEN_DIM` parameter in the [config](https://github.com/facebookresearch/ego-env/blob/a969ede32b433c12ada7fbe81f9d84d099be059c/state_prediction/config/defaults.py#L49). I've updated the README.
